services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=life
      - DB_PORT=5432
      - JWT_SECRET=seu_jwt_secret_aqui

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=life
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 